version: '3.8'

services:
 mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

 api:
   depends_on:
     - mysqldb
   build: 
      dockerfile: Dockerfile
      context: "./server"
   container_name: node_server_container      
   env_file: ./.env
   ports:
      - 8000:8000
      - 9229:9229
   environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
   stdin_open: true
   tty: true
   volumes: 
      - .:/usr/src/app
      - /usr/src/app/node_modules
   links:
      - mysqldb
   command:   
      - nodemon
      - -- inspect=0.0.0.0:9229 
      - ./src/server.ts

 client:
   depends_on:
     - mysqldb
     - api
   build: 
      dockerfile: Dockerfile
      context: "./client"
   container_name: client_container         
   ports:
     - 3000:3000
   links:
      - api
   command: yarn run dev

 jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
     - 8080:8080
     - 50000:50000    


volumes: 
  db:  