version: '3.8'

services:
 mysqldb:
   image: mysql:8.0.32
   restart: unless-stopped
   env_file: ./.env
   environment:
     - MYSQL_ROOT_PASSWORD=$DB_PASS
     - MYSQL_DATABASE=$DB_NAME
   ports:
     - $DB_PORT:$DB_PORT
   volumes:
     - db:/var/lib/mysql

 api:
   depends_on:
     - mysqldb
   build: ./tn-uptech-backend
   restart: unless-stopped
   env_file: ./.env
   ports:
     - $PORT:$PORT
   environment:
     - DB_HOST=mysqldb
     - DB_USER=$DB_USER
     - DB_PASSWORD=$DB_PASS
     - DB_NAME=$DB_NAME
     - DB_PORT=$DB_PORT
   stdin_open: true
   tty: true

jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   

nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"


volumes: 
 db:
 jenkins-data: